# Generated by Django 3.2.25 on 2024-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('complejidad', models.CharField(max_length=255)),
                ('proposito', models.CharField(max_length=255)),
                ('emocion', models.CharField(max_length=255)),
                ('analogias', models.BooleanField(default=False)),
                ('empatia', models.CharField(max_length=255)),
                ('longitudRespuesta', models.CharField(max_length=255)),
                ('retroalimentacion', models.CharField(max_length=255)),
                ('tono', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
