# Generated by Django 3.2.25 on 2024-04-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='conversaciones',
            field=models.ManyToManyField(to='core.Conversacion'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('tonopregunta', models.CharField(max_length=255)),
                ('lenguaje', models.CharField(max_length=255)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversacion')),
            ],
        ),
    ]
