# Generated by Django 3.2.25 on 2024-04-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0003_prospecto_0004_auto_20240419_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
