# Generated by Django 3.2.25 on 2024-04-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modelo_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='conversacion',
        ),
        migrations.AddField(
            model_name='conversacion',
            name='preguntas',
            field=models.ManyToManyField(to='core.Pregunta'),
        ),
    ]
