# Generated by Django 3.2.25 on 2024-04-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240428_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calGeneral', models.FloatField()),
                ('fechaEntrevista', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelo')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prospecto')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prospecto')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversacion')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reporte')),
            ],
        ),
    ]
