# Generated by Django 3.2.25 on 2024-06-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_calificacionconversacion_calificacionpregunta_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('proposito', models.CharField(max_length=255)),
                ('nombreNegocio', models.CharField(max_length=255)),
                ('descripcionNegocio', models.TextField(blank=True)),
                ('infoExtra', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fechaEntrevista',
            field=models.DateField(),
        ),
    ]
